---
---
---

### Team: Sophia Chen, Berke Kara

**Dataset:** We will be using the [Austin Police Department's Crime Reports](https://data.austintexas.gov/Public-Safety/Crime-Reports/fdj4-gpfu/about_data) data set, which contains records of incidents and crimes that the Austin Police Department has responded to and documented. Each row in the data set represents a unique crime report, detailing various aspects of the incident, such as the date, location, type of crime, and status of the case. Our primary variables of interest include crime type, location (district), and date/time of occurrence. By analyzing these variables, we can identify crime trends across different areas and time periods.

**Why:** In news, we hear a lot about how often crime is reported in Austin. This topic is important for us to investigate because we live in Austin, and often hear about various crimes in different Austin areas. Our motivation is to use the data we analyzed to find the districts that have the lowest crime so that when its time for us to look for new apartments, we can move to the district with the lowest crime, and once and for all understand if Austin is really as unsafe as media makes it out to be.

[A page from U.S. News & World Report on Austin Crime Rate and Safety.](https://realestate.usnews.com/places/texas/austin/crime)

**Research Question:**

1.  Which district has the least crime, including family violence, and how long does it take for a crime to be reported per district? (Sophia)
2.  How does time of year and location type affect the frequency of criminal activity? (Berke)

**Outcome Variable:** Number of hours it took to report a crime

**Numerical Variables:** Occured Time, Occured Date, Report Time

**Categorical Variables:** Highest Offense Description, Family Violence, Location Type, Council District
